### ISSUE TITLE
after update i get this

### ISSUE THREAD

**Issue by kivlara** [zyberspace/php-telegram-cli-client#8]
PHP Catchable fatal error:  Object of class stdClass could not be converted to string in vendor/zyberspace/telegram-cli-client/lib/Zyberspace/Telegram/Cli/RawClient.php on line 156

**Comment by zyberspace** [comment]
Hi, are you using the `example.php`? Because i just realized that i forgot to update it. So thank you for this. ;D

I changed the return value of several methods. `getContactList()` now returns an array with objects and not strings.

That's why you should stay at the same minor-version (`~0.3.0` or `0.3.*` for example).
See [SemVer](http://semver.org/spec/v2.0.0.html) and the [composer-doc](https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-) for this.

From the README:
> API-Stability
> The api of the commands wrappers will definitely change in the future, for example `getHistory()` only returns the raw answer of the `telegram-cli` right now and is not really useful. Therefore you should not use this in production yet.
> 
> If you still want to use this in your project, make sure you stay at the same minor-version (`~0.1.0` or `0.1.*` for example).

Also never use `dev-master` as version, as this is always the development version. All stable releases are tagged when they are ready so there is no need for `dev-master`.

**Comment by zyberspace** [comment]
Closed as there are no new informations.
