### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by mirafi** [zyberspace/php-telegram-cli-client#9]
Hi,
while running this script " ./bin/telegram-cli --json -dWS /tmp/tg.sck & " in cmd Windows pc
i got 
![er](https://cloud.githubusercontent.com/assets/11525427/8667440/c75bda70-2a21-11e5-9d71-b2d46c5def4a.jpg)
would please tell me where im wrong ?

**Comment by zyberspace** [comment]
Hi, there are two reasons the command does not work.

> (execute it from the dir, where you installed telegram-cli, not the php-client)

This means you need to [install telegram-cli](https://github.com/vysheng/tg/#installation) first and then execute the command from the dir where you installed it.

If you do so, you will see, that there are no install instructions for windows. This is because **telegram-cli does not work on windows** ([yet?](https://github.com/vysheng/tg/issues?utf8=%E2%9C%93&q=windows)).

If you really want to develop on windows, you maybe want to set up a virtual box running linux, the telegram-cli and your webserver (**unix**-file-sockets are also not available on windows).

Hope i could help you, Eric :)

**Comment by mirafi** [comment]
Thanks :)
